// Code generated by MockGen. DO NOT EDIT.
// Source: forwarder.go
//
// Generated by this command:
//
//	mockgen -source=forwarder.go -destination=../../mocks/usecase/forwarder.go.mock.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockIForwardUC is a mock of IForwardUC interface.
type MockIForwardUC struct {
	ctrl     *gomock.Controller
	recorder *MockIForwardUCMockRecorder
	isgomock struct{}
}

// MockIForwardUCMockRecorder is the mock recorder for MockIForwardUC.
type MockIForwardUCMockRecorder struct {
	mock *MockIForwardUC
}

// NewMockIForwardUC creates a new mock instance.
func NewMockIForwardUC(ctrl *gomock.Controller) *MockIForwardUC {
	mock := &MockIForwardUC{ctrl: ctrl}
	mock.recorder = &MockIForwardUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIForwardUC) EXPECT() *MockIForwardUCMockRecorder {
	return m.recorder
}

// ResponseMockData mocks base method.
func (m *MockIForwardUC) ResponseMockData(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseMockData", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResponseMockData indicates an expected call of ResponseMockData.
func (mr *MockIForwardUCMockRecorder) ResponseMockData(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseMockData", reflect.TypeOf((*MockIForwardUC)(nil).ResponseMockData), c)
}

// ResponsePublicMockData mocks base method.
func (m *MockIForwardUC) ResponsePublicMockData(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponsePublicMockData", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResponsePublicMockData indicates an expected call of ResponsePublicMockData.
func (mr *MockIForwardUCMockRecorder) ResponsePublicMockData(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponsePublicMockData", reflect.TypeOf((*MockIForwardUC)(nil).ResponsePublicMockData), c)
}
