// Code generated by MockGen. DO NOT EDIT.
// Source: grpc_forwarder.go
//
// Generated by this command:
//
//	mockgen -source=grpc_forwarder.go -destination=../../mocks/usecase/grpc_forwarder.go.mock.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	codes "google.golang.org/grpc/codes"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// MockIGRPCForwardUC is a mock of IGRPCForwardUC interface.
type MockIGRPCForwardUC struct {
	ctrl     *gomock.Controller
	recorder *MockIGRPCForwardUCMockRecorder
	isgomock struct{}
}

// MockIGRPCForwardUCMockRecorder is the mock recorder for MockIGRPCForwardUC.
type MockIGRPCForwardUCMockRecorder struct {
	mock *MockIGRPCForwardUC
}

// NewMockIGRPCForwardUC creates a new mock instance.
func NewMockIGRPCForwardUC(ctrl *gomock.Controller) *MockIGRPCForwardUC {
	mock := &MockIGRPCForwardUC{ctrl: ctrl}
	mock.recorder = &MockIGRPCForwardUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGRPCForwardUC) EXPECT() *MockIGRPCForwardUCMockRecorder {
	return m.recorder
}

// HandleCall mocks base method.
func (m *MockIGRPCForwardUC) HandleCall(ctx context.Context, fullMethod string, reqBytes []byte, featureName string, accountID *string) (*structpb.Struct, codes.Code, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCall", ctx, fullMethod, reqBytes, featureName, accountID)
	ret0, _ := ret[0].(*structpb.Struct)
	ret1, _ := ret[1].(codes.Code)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleCall indicates an expected call of HandleCall.
func (mr *MockIGRPCForwardUCMockRecorder) HandleCall(ctx, fullMethod, reqBytes, featureName, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCall", reflect.TypeOf((*MockIGRPCForwardUC)(nil).HandleCall), ctx, fullMethod, reqBytes, featureName, accountID)
}
