// Code generated by MockGen. DO NOT EDIT.
// Source: loadtest_controller.go

// Package controller is a generated GoMock package.
package controller

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockILoadTestController is a mock of ILoadTestController interface.
type MockILoadTestController struct {
	ctrl     *gomock.Controller
	recorder *MockILoadTestControllerMockRecorder
}

// MockILoadTestControllerMockRecorder is the mock recorder for MockILoadTestController.
type MockILoadTestControllerMockRecorder struct {
	mock *MockILoadTestController
}

// NewMockILoadTestController creates a new mock instance.
func NewMockILoadTestController(ctrl *gomock.Controller) *MockILoadTestController {
	mock := &MockILoadTestController{ctrl: ctrl}
	mock.recorder = &MockILoadTestControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoadTestController) EXPECT() *MockILoadTestControllerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockILoadTestController) RegisterRoutes(g *echo.Group) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", g)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockILoadTestControllerMockRecorder) RegisterRoutes(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockILoadTestController)(nil).RegisterRoutes), g)
}
