// Code generated by MockGen. DO NOT EDIT.
// Source: account_scenario.go
//
// Generated by this command:
//
//	mockgen -source=account_scenario.go -destination=../../mocks/repository/account_scenario.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIAccountScenarioRepository is a mock of IAccountScenarioRepository interface.
type MockIAccountScenarioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountScenarioRepositoryMockRecorder
	isgomock struct{}
}

// MockIAccountScenarioRepositoryMockRecorder is the mock recorder for MockIAccountScenarioRepository.
type MockIAccountScenarioRepositoryMockRecorder struct {
	mock *MockIAccountScenarioRepository
}

// NewMockIAccountScenarioRepository creates a new mock instance.
func NewMockIAccountScenarioRepository(ctrl *gomock.Controller) *MockIAccountScenarioRepository {
	mock := &MockIAccountScenarioRepository{ctrl: ctrl}
	mock.recorder = &MockIAccountScenarioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountScenarioRepository) EXPECT() *MockIAccountScenarioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIAccountScenarioRepository) Create(ctx context.Context, as *domain.AccountScenario) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, as)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIAccountScenarioRepositoryMockRecorder) Create(ctx, as any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountScenarioRepository)(nil).Create), ctx, as)
}

// DeactivateAllAccountSpecificMappings mocks base method.
func (m *MockIAccountScenarioRepository) DeactivateAllAccountSpecificMappings(ctx context.Context, featureName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAllAccountSpecificMappings", ctx, featureName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAllAccountSpecificMappings indicates an expected call of DeactivateAllAccountSpecificMappings.
func (mr *MockIAccountScenarioRepositoryMockRecorder) DeactivateAllAccountSpecificMappings(ctx, featureName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAllAccountSpecificMappings", reflect.TypeOf((*MockIAccountScenarioRepository)(nil).DeactivateAllAccountSpecificMappings), ctx, featureName)
}

// DeactivateByFeatureAndAccount mocks base method.
func (m *MockIAccountScenarioRepository) DeactivateByFeatureAndAccount(ctx context.Context, featureName string, accountId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateByFeatureAndAccount", ctx, featureName, accountId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateByFeatureAndAccount indicates an expected call of DeactivateByFeatureAndAccount.
func (mr *MockIAccountScenarioRepositoryMockRecorder) DeactivateByFeatureAndAccount(ctx, featureName, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateByFeatureAndAccount", reflect.TypeOf((*MockIAccountScenarioRepository)(nil).DeactivateByFeatureAndAccount), ctx, featureName, accountId)
}

// GetActiveScenario mocks base method.
func (m *MockIAccountScenarioRepository) GetActiveScenario(ctx context.Context, featureName string, accountId *string) (*domain.AccountScenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveScenario", ctx, featureName, accountId)
	ret0, _ := ret[0].(*domain.AccountScenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveScenario indicates an expected call of GetActiveScenario.
func (mr *MockIAccountScenarioRepositoryMockRecorder) GetActiveScenario(ctx, featureName, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveScenario", reflect.TypeOf((*MockIAccountScenarioRepository)(nil).GetActiveScenario), ctx, featureName, accountId)
}
