// Code generated by MockGen. DO NOT EDIT.
// Source: feature.go
//
// Generated by this command:
//
//	mockgen -source=feature.go -destination=../../mocks/repository/feature.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIFeatureRepository is a mock of IFeatureRepository interface.
type MockIFeatureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIFeatureRepositoryMockRecorder
	isgomock struct{}
}

// MockIFeatureRepositoryMockRecorder is the mock recorder for MockIFeatureRepository.
type MockIFeatureRepositoryMockRecorder struct {
	mock *MockIFeatureRepository
}

// NewMockIFeatureRepository creates a new mock instance.
func NewMockIFeatureRepository(ctrl *gomock.Controller) *MockIFeatureRepository {
	mock := &MockIFeatureRepository{ctrl: ctrl}
	mock.recorder = &MockIFeatureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFeatureRepository) EXPECT() *MockIFeatureRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIFeatureRepository) Create(ctx context.Context, f *domain.Feature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIFeatureRepositoryMockRecorder) Create(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIFeatureRepository)(nil).Create), ctx, f)
}

// DeleteById mocks base method.
func (m *MockIFeatureRepository) DeleteById(ctx context.Context, featureId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, featureId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIFeatureRepositoryMockRecorder) DeleteById(ctx, featureId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIFeatureRepository)(nil).DeleteById), ctx, featureId)
}

// FindById mocks base method.
func (m *MockIFeatureRepository) FindById(ctx context.Context, featureId primitive.ObjectID) (*domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, featureId)
	ret0, _ := ret[0].(*domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockIFeatureRepositoryMockRecorder) FindById(ctx, featureId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockIFeatureRepository)(nil).FindById), ctx, featureId)
}

// FindByName mocks base method.
func (m *MockIFeatureRepository) FindByName(ctx context.Context, name string) (*domain.Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*domain.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockIFeatureRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockIFeatureRepository)(nil).FindByName), ctx, name)
}

// ListAllPaginated mocks base method.
func (m *MockIFeatureRepository) ListAllPaginated(ctx context.Context, params domain.PaginationParams) ([]domain.Feature, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPaginated", ctx, params)
	ret0, _ := ret[0].([]domain.Feature)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllPaginated indicates an expected call of ListAllPaginated.
func (mr *MockIFeatureRepositoryMockRecorder) ListAllPaginated(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPaginated", reflect.TypeOf((*MockIFeatureRepository)(nil).ListAllPaginated), ctx, params)
}

// SearchByName mocks base method.
func (m *MockIFeatureRepository) SearchByName(ctx context.Context, query string, params domain.PaginationParams) ([]domain.Feature, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByName", ctx, query, params)
	ret0, _ := ret[0].([]domain.Feature)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByName indicates an expected call of SearchByName.
func (mr *MockIFeatureRepositoryMockRecorder) SearchByName(ctx, query, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByName", reflect.TypeOf((*MockIFeatureRepository)(nil).SearchByName), ctx, query, params)
}

// UpdateByObjectID mocks base method.
func (m *MockIFeatureRepository) UpdateByObjectID(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByObjectID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByObjectID indicates an expected call of UpdateByObjectID.
func (mr *MockIFeatureRepositoryMockRecorder) UpdateByObjectID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByObjectID", reflect.TypeOf((*MockIFeatureRepository)(nil).UpdateByObjectID), ctx, id, update)
}
