// Code generated by MockGen. DO NOT EDIT.
// Source: grpc_mockapi.go
//
// Generated by this command:
//
//	mockgen -source=grpc_mockapi.go -destination=../../mocks/repository/grpc_mockapi.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIGRPCMockAPIRepository is a mock of IGRPCMockAPIRepository interface.
type MockIGRPCMockAPIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIGRPCMockAPIRepositoryMockRecorder
	isgomock struct{}
}

// MockIGRPCMockAPIRepositoryMockRecorder is the mock recorder for MockIGRPCMockAPIRepository.
type MockIGRPCMockAPIRepositoryMockRecorder struct {
	mock *MockIGRPCMockAPIRepository
}

// NewMockIGRPCMockAPIRepository creates a new mock instance.
func NewMockIGRPCMockAPIRepository(ctrl *gomock.Controller) *MockIGRPCMockAPIRepository {
	mock := &MockIGRPCMockAPIRepository{ctrl: ctrl}
	mock.recorder = &MockIGRPCMockAPIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGRPCMockAPIRepository) EXPECT() *MockIGRPCMockAPIRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockIGRPCMockAPIRepository) Create(ctx context.Context, m *domain.GRPCMockAPI) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).Create), ctx, m)
}

// DeleteByID mocks base method.
func (m *MockIGRPCMockAPIRepository) DeleteByID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).DeleteByID), ctx, id)
}

// FindByFeatureScenarioServiceMethodAndHash mocks base method.
func (m *MockIGRPCMockAPIRepository) FindByFeatureScenarioServiceMethodAndHash(ctx context.Context, featureName, scenarioName, serviceName, methodName, hashInput string) (*domain.GRPCMockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFeatureScenarioServiceMethodAndHash", ctx, featureName, scenarioName, serviceName, methodName, hashInput)
	ret0, _ := ret[0].(*domain.GRPCMockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFeatureScenarioServiceMethodAndHash indicates an expected call of FindByFeatureScenarioServiceMethodAndHash.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) FindByFeatureScenarioServiceMethodAndHash(ctx, featureName, scenarioName, serviceName, methodName, hashInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFeatureScenarioServiceMethodAndHash", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).FindByFeatureScenarioServiceMethodAndHash), ctx, featureName, scenarioName, serviceName, methodName, hashInput)
}

// FindByID mocks base method.
func (m *MockIGRPCMockAPIRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*domain.GRPCMockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.GRPCMockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).FindByID), ctx, id)
}

// ListAll mocks base method.
func (m *MockIGRPCMockAPIRepository) ListAll(ctx context.Context) ([]domain.GRPCMockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]domain.GRPCMockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).ListAll), ctx)
}

// ListByFeatureAndScenario mocks base method.
func (m *MockIGRPCMockAPIRepository) ListByFeatureAndScenario(ctx context.Context, featureName, scenarioName string) ([]domain.GRPCMockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFeatureAndScenario", ctx, featureName, scenarioName)
	ret0, _ := ret[0].([]domain.GRPCMockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFeatureAndScenario indicates an expected call of ListByFeatureAndScenario.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) ListByFeatureAndScenario(ctx, featureName, scenarioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFeatureAndScenario", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).ListByFeatureAndScenario), ctx, featureName, scenarioName)
}

// UpdateByID mocks base method.
func (m *MockIGRPCMockAPIRepository) UpdateByID(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIGRPCMockAPIRepositoryMockRecorder) UpdateByID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIGRPCMockAPIRepository)(nil).UpdateByID), ctx, id, update)
}
