// Code generated by MockGen. DO NOT EDIT.
// Source: loadtest_scenario.go
//
// Generated by this command:
//
//	mockgen -source=loadtest_scenario.go -destination=../../mocks/repository/loadtest_scenario.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockILoadTestScenarioRepository is a mock of ILoadTestScenarioRepository interface.
type MockILoadTestScenarioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILoadTestScenarioRepositoryMockRecorder
	isgomock struct{}
}

// MockILoadTestScenarioRepositoryMockRecorder is the mock recorder for MockILoadTestScenarioRepository.
type MockILoadTestScenarioRepositoryMockRecorder struct {
	mock *MockILoadTestScenarioRepository
}

// NewMockILoadTestScenarioRepository creates a new mock instance.
func NewMockILoadTestScenarioRepository(ctrl *gomock.Controller) *MockILoadTestScenarioRepository {
	mock := &MockILoadTestScenarioRepository{ctrl: ctrl}
	mock.recorder = &MockILoadTestScenarioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoadTestScenarioRepository) EXPECT() *MockILoadTestScenarioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockILoadTestScenarioRepository) Create(ctx context.Context, s *domain.LoadTestScenario) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockILoadTestScenarioRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockILoadTestScenarioRepository) GetByID(ctx context.Context, id primitive.ObjectID) (*domain.LoadTestScenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.LoadTestScenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockILoadTestScenarioRepository) GetByName(ctx context.Context, name string) (*domain.LoadTestScenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.LoadTestScenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).GetByName), ctx, name)
}

// ListPaginated mocks base method.
func (m *MockILoadTestScenarioRepository) ListPaginated(ctx context.Context, params domain.PaginationParams) ([]domain.LoadTestScenario, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaginated", ctx, params)
	ret0, _ := ret[0].([]domain.LoadTestScenario)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPaginated indicates an expected call of ListPaginated.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) ListPaginated(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaginated", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).ListPaginated), ctx, params)
}

// SearchByName mocks base method.
func (m *MockILoadTestScenarioRepository) SearchByName(ctx context.Context, query string, params domain.PaginationParams) ([]domain.LoadTestScenario, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByName", ctx, query, params)
	ret0, _ := ret[0].([]domain.LoadTestScenario)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByName indicates an expected call of SearchByName.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) SearchByName(ctx, query, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByName", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).SearchByName), ctx, query, params)
}

// Update mocks base method.
func (m *MockILoadTestScenarioRepository) Update(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockILoadTestScenarioRepositoryMockRecorder) Update(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockILoadTestScenarioRepository)(nil).Update), ctx, id, update)
}
