// Code generated by MockGen. DO NOT EDIT.
// Source: mockapi.go
//
// Generated by this command:
//
//	mockgen -source=mockapi.go -destination=../../mocks/repository/mockapi.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIMockAPIRepository is a mock of IMockAPIRepository interface.
type MockIMockAPIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMockAPIRepositoryMockRecorder
	isgomock struct{}
}

// MockIMockAPIRepositoryMockRecorder is the mock recorder for MockIMockAPIRepository.
type MockIMockAPIRepositoryMockRecorder struct {
	mock *MockIMockAPIRepository
}

// NewMockIMockAPIRepository creates a new mock instance.
func NewMockIMockAPIRepository(ctrl *gomock.Controller) *MockIMockAPIRepository {
	mock := &MockIMockAPIRepository{ctrl: ctrl}
	mock.recorder = &MockIMockAPIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMockAPIRepository) EXPECT() *MockIMockAPIRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockIMockAPIRepository) Create(ctx context.Context, m *domain.MockAPI) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIMockAPIRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIMockAPIRepository)(nil).Create), ctx, m)
}

// FindByFeatureScenarioPathMethodAndHash mocks base method.
func (m *MockIMockAPIRepository) FindByFeatureScenarioPathMethodAndHash(ctx context.Context, featureName, scenarioName, path, method, hashInput string) (*domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFeatureScenarioPathMethodAndHash", ctx, featureName, scenarioName, path, method, hashInput)
	ret0, _ := ret[0].(*domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFeatureScenarioPathMethodAndHash indicates an expected call of FindByFeatureScenarioPathMethodAndHash.
func (mr *MockIMockAPIRepositoryMockRecorder) FindByFeatureScenarioPathMethodAndHash(ctx, featureName, scenarioName, path, method, hashInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFeatureScenarioPathMethodAndHash", reflect.TypeOf((*MockIMockAPIRepository)(nil).FindByFeatureScenarioPathMethodAndHash), ctx, featureName, scenarioName, path, method, hashInput)
}

// ListByScenarioNamePaginated mocks base method.
func (m *MockIMockAPIRepository) ListByScenarioNamePaginated(ctx context.Context, scenarioName string, params domain.PaginationParams) ([]domain.MockAPI, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByScenarioNamePaginated", ctx, scenarioName, params)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByScenarioNamePaginated indicates an expected call of ListByScenarioNamePaginated.
func (mr *MockIMockAPIRepositoryMockRecorder) ListByScenarioNamePaginated(ctx, scenarioName, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByScenarioNamePaginated", reflect.TypeOf((*MockIMockAPIRepository)(nil).ListByScenarioNamePaginated), ctx, scenarioName, params)
}

// SearchByScenarioAndNameOrPath mocks base method.
func (m *MockIMockAPIRepository) SearchByScenarioAndNameOrPath(ctx context.Context, scenarioName, query string, params domain.PaginationParams) ([]domain.MockAPI, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByScenarioAndNameOrPath", ctx, scenarioName, query, params)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByScenarioAndNameOrPath indicates an expected call of SearchByScenarioAndNameOrPath.
func (mr *MockIMockAPIRepositoryMockRecorder) SearchByScenarioAndNameOrPath(ctx, scenarioName, query, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByScenarioAndNameOrPath", reflect.TypeOf((*MockIMockAPIRepository)(nil).SearchByScenarioAndNameOrPath), ctx, scenarioName, query, params)
}

// UpdateByObjectID mocks base method.
func (m *MockIMockAPIRepository) UpdateByObjectID(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByObjectID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByObjectID indicates an expected call of UpdateByObjectID.
func (mr *MockIMockAPIRepositoryMockRecorder) UpdateByObjectID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByObjectID", reflect.TypeOf((*MockIMockAPIRepository)(nil).UpdateByObjectID), ctx, id, update)
}
