// Code generated by MockGen. DO NOT EDIT.
// Source: mockapi.go
//
// Generated by this command:
//
//	mockgen -source=mockapi.go -destination=../../mocks/repository/mockapi.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIMockAPIRepository is a mock of IMockAPIRepository interface.
type MockIMockAPIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMockAPIRepositoryMockRecorder
	isgomock struct{}
}

// MockIMockAPIRepositoryMockRecorder is the mock recorder for MockIMockAPIRepository.
type MockIMockAPIRepositoryMockRecorder struct {
	mock *MockIMockAPIRepository
}

// NewMockIMockAPIRepository creates a new mock instance.
func NewMockIMockAPIRepository(ctrl *gomock.Controller) *MockIMockAPIRepository {
	mock := &MockIMockAPIRepository{ctrl: ctrl}
	mock.recorder = &MockIMockAPIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMockAPIRepository) EXPECT() *MockIMockAPIRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockIMockAPIRepository) Create(ctx context.Context, m *domain.MockAPI) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIMockAPIRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIMockAPIRepository)(nil).Create), ctx, m)
}

// DeletByObjectID mocks base method.
func (m *MockIMockAPIRepository) DeletByObjectID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletByObjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletByObjectID indicates an expected call of DeletByObjectID.
func (mr *MockIMockAPIRepositoryMockRecorder) DeletByObjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletByObjectID", reflect.TypeOf((*MockIMockAPIRepository)(nil).DeletByObjectID), ctx, id)
}

// DeleteByFeatureName mocks base method.
func (m *MockIMockAPIRepository) DeleteByFeatureName(ctx context.Context, featureName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByFeatureName", ctx, featureName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByFeatureName indicates an expected call of DeleteByFeatureName.
func (mr *MockIMockAPIRepositoryMockRecorder) DeleteByFeatureName(ctx, featureName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByFeatureName", reflect.TypeOf((*MockIMockAPIRepository)(nil).DeleteByFeatureName), ctx, featureName)
}

// DeleteByScenarioName mocks base method.
func (m *MockIMockAPIRepository) DeleteByScenarioName(ctx context.Context, scenarioName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByScenarioName", ctx, scenarioName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByScenarioName indicates an expected call of DeleteByScenarioName.
func (mr *MockIMockAPIRepositoryMockRecorder) DeleteByScenarioName(ctx, scenarioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByScenarioName", reflect.TypeOf((*MockIMockAPIRepository)(nil).DeleteByScenarioName), ctx, scenarioName)
}

// FindByFeatureScenarioPathMethodAndHash mocks base method.
func (m *MockIMockAPIRepository) FindByFeatureScenarioPathMethodAndHash(ctx context.Context, featureName, scenarioName, path, method, hashInput string) (*domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFeatureScenarioPathMethodAndHash", ctx, featureName, scenarioName, path, method, hashInput)
	ret0, _ := ret[0].(*domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFeatureScenarioPathMethodAndHash indicates an expected call of FindByFeatureScenarioPathMethodAndHash.
func (mr *MockIMockAPIRepositoryMockRecorder) FindByFeatureScenarioPathMethodAndHash(ctx, featureName, scenarioName, path, method, hashInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFeatureScenarioPathMethodAndHash", reflect.TypeOf((*MockIMockAPIRepository)(nil).FindByFeatureScenarioPathMethodAndHash), ctx, featureName, scenarioName, path, method, hashInput)
}

// FindByNameAndFeatureAndScenario mocks base method.
func (m *MockIMockAPIRepository) FindByNameAndFeatureAndScenario(ctx context.Context, mockName, featureName, sceanrioName string) (*domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameAndFeatureAndScenario", ctx, mockName, featureName, sceanrioName)
	ret0, _ := ret[0].(*domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameAndFeatureAndScenario indicates an expected call of FindByNameAndFeatureAndScenario.
func (mr *MockIMockAPIRepositoryMockRecorder) FindByNameAndFeatureAndScenario(ctx, mockName, featureName, sceanrioName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameAndFeatureAndScenario", reflect.TypeOf((*MockIMockAPIRepository)(nil).FindByNameAndFeatureAndScenario), ctx, mockName, featureName, sceanrioName)
}

// FindByObjectID mocks base method.
func (m *MockIMockAPIRepository) FindByObjectID(ctx context.Context, id primitive.ObjectID) (*domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByObjectID", ctx, id)
	ret0, _ := ret[0].(*domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByObjectID indicates an expected call of FindByObjectID.
func (mr *MockIMockAPIRepositoryMockRecorder) FindByObjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByObjectID", reflect.TypeOf((*MockIMockAPIRepository)(nil).FindByObjectID), ctx, id)
}

// ListActiveAPIsByScenario mocks base method.
func (m *MockIMockAPIRepository) ListActiveAPIsByScenario(ctx context.Context, scenarios []string) ([]domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveAPIsByScenario", ctx, scenarios)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveAPIsByScenario indicates an expected call of ListActiveAPIsByScenario.
func (mr *MockIMockAPIRepositoryMockRecorder) ListActiveAPIsByScenario(ctx, scenarios any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveAPIsByScenario", reflect.TypeOf((*MockIMockAPIRepository)(nil).ListActiveAPIsByScenario), ctx, scenarios)
}

// ListAllActiveAPIs mocks base method.
func (m *MockIMockAPIRepository) ListAllActiveAPIs(ctx context.Context) ([]domain.MockAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllActiveAPIs", ctx)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllActiveAPIs indicates an expected call of ListAllActiveAPIs.
func (mr *MockIMockAPIRepositoryMockRecorder) ListAllActiveAPIs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllActiveAPIs", reflect.TypeOf((*MockIMockAPIRepository)(nil).ListAllActiveAPIs), ctx)
}

// ListByScenarioNamePaginated mocks base method.
func (m *MockIMockAPIRepository) ListByScenarioNamePaginated(ctx context.Context, scenarioName string, params domain.PaginationParams) ([]domain.MockAPI, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByScenarioNamePaginated", ctx, scenarioName, params)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByScenarioNamePaginated indicates an expected call of ListByScenarioNamePaginated.
func (mr *MockIMockAPIRepositoryMockRecorder) ListByScenarioNamePaginated(ctx, scenarioName, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByScenarioNamePaginated", reflect.TypeOf((*MockIMockAPIRepository)(nil).ListByScenarioNamePaginated), ctx, scenarioName, params)
}

// SearchByScenarioAndNameOrPath mocks base method.
func (m *MockIMockAPIRepository) SearchByScenarioAndNameOrPath(ctx context.Context, scenarioName, query string, params domain.PaginationParams) ([]domain.MockAPI, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByScenarioAndNameOrPath", ctx, scenarioName, query, params)
	ret0, _ := ret[0].([]domain.MockAPI)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByScenarioAndNameOrPath indicates an expected call of SearchByScenarioAndNameOrPath.
func (mr *MockIMockAPIRepositoryMockRecorder) SearchByScenarioAndNameOrPath(ctx, scenarioName, query, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByScenarioAndNameOrPath", reflect.TypeOf((*MockIMockAPIRepository)(nil).SearchByScenarioAndNameOrPath), ctx, scenarioName, query, params)
}

// UpdateByObjectID mocks base method.
func (m *MockIMockAPIRepository) UpdateByObjectID(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByObjectID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByObjectID indicates an expected call of UpdateByObjectID.
func (mr *MockIMockAPIRepositoryMockRecorder) UpdateByObjectID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByObjectID", reflect.TypeOf((*MockIMockAPIRepository)(nil).UpdateByObjectID), ctx, id, update)
}
