// Code generated by MockGen. DO NOT EDIT.
// Source: scenario.go
//
// Generated by this command:
//
//	mockgen -source=scenario.go -destination=../../mocks/repository/scenario.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/mocktool/internal/domain"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockIScenarioRepository is a mock of IScenarioRepository interface.
type MockIScenarioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIScenarioRepositoryMockRecorder
	isgomock struct{}
}

// MockIScenarioRepositoryMockRecorder is the mock recorder for MockIScenarioRepository.
type MockIScenarioRepositoryMockRecorder struct {
	mock *MockIScenarioRepository
}

// NewMockIScenarioRepository creates a new mock instance.
func NewMockIScenarioRepository(ctrl *gomock.Controller) *MockIScenarioRepository {
	mock := &MockIScenarioRepository{ctrl: ctrl}
	mock.recorder = &MockIScenarioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScenarioRepository) EXPECT() *MockIScenarioRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIScenarioRepository) Create(ctx context.Context, s *domain.Scenario) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIScenarioRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIScenarioRepository)(nil).Create), ctx, s)
}

// DeleteByObjectID mocks base method.
func (m *MockIScenarioRepository) DeleteByObjectID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByObjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByObjectID indicates an expected call of DeleteByObjectID.
func (mr *MockIScenarioRepositoryMockRecorder) DeleteByObjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByObjectID", reflect.TypeOf((*MockIScenarioRepository)(nil).DeleteByObjectID), ctx, id)
}

// FindByFeatureNameAndName mocks base method.
func (m *MockIScenarioRepository) FindByFeatureNameAndName(ctx context.Context, featureName, name string) (*domain.Scenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFeatureNameAndName", ctx, featureName, name)
	ret0, _ := ret[0].(*domain.Scenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFeatureNameAndName indicates an expected call of FindByFeatureNameAndName.
func (mr *MockIScenarioRepositoryMockRecorder) FindByFeatureNameAndName(ctx, featureName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFeatureNameAndName", reflect.TypeOf((*MockIScenarioRepository)(nil).FindByFeatureNameAndName), ctx, featureName, name)
}

// GetByObjectID mocks base method.
func (m *MockIScenarioRepository) GetByObjectID(ctx context.Context, id primitive.ObjectID) (*domain.Scenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByObjectID", ctx, id)
	ret0, _ := ret[0].(*domain.Scenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByObjectID indicates an expected call of GetByObjectID.
func (mr *MockIScenarioRepositoryMockRecorder) GetByObjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByObjectID", reflect.TypeOf((*MockIScenarioRepository)(nil).GetByObjectID), ctx, id)
}

// ListByFeatureNamePaginated mocks base method.
func (m *MockIScenarioRepository) ListByFeatureNamePaginated(ctx context.Context, featureName string, params domain.PaginationParams) ([]domain.Scenario, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFeatureNamePaginated", ctx, featureName, params)
	ret0, _ := ret[0].([]domain.Scenario)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByFeatureNamePaginated indicates an expected call of ListByFeatureNamePaginated.
func (mr *MockIScenarioRepositoryMockRecorder) ListByFeatureNamePaginated(ctx, featureName, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFeatureNamePaginated", reflect.TypeOf((*MockIScenarioRepository)(nil).ListByFeatureNamePaginated), ctx, featureName, params)
}

// SearchByFeatureAndName mocks base method.
func (m *MockIScenarioRepository) SearchByFeatureAndName(ctx context.Context, featureName, query string, params domain.PaginationParams) ([]domain.Scenario, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByFeatureAndName", ctx, featureName, query, params)
	ret0, _ := ret[0].([]domain.Scenario)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByFeatureAndName indicates an expected call of SearchByFeatureAndName.
func (mr *MockIScenarioRepositoryMockRecorder) SearchByFeatureAndName(ctx, featureName, query, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByFeatureAndName", reflect.TypeOf((*MockIScenarioRepository)(nil).SearchByFeatureAndName), ctx, featureName, query, params)
}

// UpdateByObjectID mocks base method.
func (m *MockIScenarioRepository) UpdateByObjectID(ctx context.Context, id primitive.ObjectID, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByObjectID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByObjectID indicates an expected call of UpdateByObjectID.
func (mr *MockIScenarioRepositoryMockRecorder) UpdateByObjectID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByObjectID", reflect.TypeOf((*MockIScenarioRepository)(nil).UpdateByObjectID), ctx, id, update)
}
